name: ci
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install npm@latest
        run: npm install npm -g

      - name: Install dependencies
        run: npm ci

      - run: npm run lint