name: Deploy
on:
  release:
    types: [created]

jobs:
  check:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn lint

  deploy:
    name: npm publish
    runs-on: ubuntu-latest
    needs: check

    strategy:
      matrix:
        pkg: [browserslist,eslint,jest,prettier]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/${{ matrix.pkg }}/package.json
